name: pyopia
channels:
    - conda-forge
dependencies:    # These are the conda packages
    - python=3.8
    - pip
    - flake8
    - numpy>=1.20.1
    - pandas
    - h5py=2.10.0
    - pytables
    - scipy
    - scikit-image
    - pytest
    - imageio
    - pip: # The following packages are installed with pip
        - docopt
        - tqdm
        - setuptools
        - pytest-error-for-skips
        - tensorflow-cpu==2.3.1
        - sphinx_rtd_theme==0.5.0
        - sphinxcontrib-napoleon==0.7
