name: pyopia
channels:
    - conda-forge
dependencies:    # These are the conda packages
    - python=3.10
    - pip
    - flake8
    - numpy>=1.20.1
    - pandas
    - h5py
    - pytables=3.6.1
    - scipy
    - scikit-image
    - pytest>=7.2.0
    - imageio
    - pip: # The following packages are installed with pip
        - docopt
        - tqdm
        - setuptools
        - pytest-error-for-skips
        - sphinx_rtd_theme>=0.5.0
        - sphinxcontrib-napoleon>=0.7
        - tensorflow-cpu==2.10.1
        - numpy==1.23.4
        - ipykernel>=6.19.4
        - gdown
        - cmocean
        - jupyter-book
