name: Windows build and test

on: [push]

env:
  IMAGE_NAME: sintef/pyopia
  IMAGE_TAG: github-ci

jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 60

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install pyopia environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pyopia
          environment-file: environment.yml

      - name: Check pyopia environment
        shell: cmd /C CALL {0}
        run: >-
          conda info && conda list && conda env list

      - name: Setup develop
        shell: cmd /C CALL {0}
        run: >-
          activate pyopia &&
          python setup.py develop

      - name: Setup test
        shell: cmd /C CALL {0}
        run: >-
          dir &&
          activate pyopia &&
          python setup.py test
