name: Windows build and test

on: [pull_request]

env:
  IMAGE_NAME: sintef/pyopia
  IMAGE_TAG: github-ci

jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 60

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install pyopia environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pyopia
          environment-file: environment.yml

      - name: Setup develop
        shell: cmd /C CALL {0}
        run: >-
          activate pyopia &&
          poetry install

      - name: Setup test
        shell: cmd /C CALL {0}
        run: >-
          dir &&
          activate pyopia &&
          poetry run pytest
